using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Concurrent;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Input;
using userinterface.Commands;
using userspace_backend;
using BE = userspace_backend.Model;

namespace userinterface.ViewModels.Profile
{
    public partial class ProfileListViewModel : ViewModelBase
    {
        private const int MaxProfileAttempts = 10;
        private readonly BE.IProfilesModel profilesModel;
        private readonly SemaphoreSlim operationQueue = new(1, 1);
        private readonly ConcurrentQueue<Func<Task>> pendingOperations = new();
        private volatile bool isProcessingQueue = false;
        private Views.Profile.ProfileListView? profileListView;

        [ObservableProperty]
        private BE.IProfileModel? selectedProfile;

        public event Action<BE.IProfileModel>? SelectedProfileChanged;

        partial void OnSelectedProfileChanged(BE.IProfileModel? value)
        {
            if (value != null) SelectedProfileChanged?.Invoke(value);

            if (profileListView != null)
            {
                profileListView.SetSelectedProfile(value, false);
            }
        }

        public ProfileListViewModel(IBackEnd backEnd)
        {
            profilesModel = backEnd?.Profiles ?? throw new System.ArgumentNullException(nameof(backEnd));
            AddProfileCommand = new RelayCommand(TryAddProfile);
        }

        public ReadOnlyObservableCollection<BE.IProfileModel> Profiles => profilesModel.Elements;
        public ICommand AddProfileCommand { get; }

        public void SetView(Views.Profile.ProfileListView view)
        {
            profileListView = view;
        }

        public void TryAddProfile()
        {
            // Queue the operation to prevent overlapping
            pendingOperations.Enqueue(async () => await TryAddProfileAsync());
            _ = ProcessOperationQueue();
        }

        private async Task TryAddProfileAsync()
        {
            var startTime = DateTime.Now;

            var profileName = GenerateProfileName();
            if (TryAddProfileWithName(profileName))
            {
                var backendAddTime = DateTime.Now;

                MoveNewProfileToOptimalPosition(profileName);

                var reorderTime = DateTime.Now;

                // Wait for any animations to complete before allowing next operation
                await WaitForAnimationsToComplete();

                var completionTime = DateTime.Now;
            }
        }

        private void MoveNewProfileToOptimalPosition(string profileName)
        {
            // TODO: Implement profile reordering with new readonly collection
            // For now, profiles are added at the end
        }

        private int FindOptimalInsertPosition()
        {
            // Find the first "Profile X" entry (auto-generated name) after the first profile
            for (int i = 1; i < Profiles.Count; i++)
            {
                var profile = Profiles[i];
                if (IsAutoGeneratedProfileName(profile.Name.ModelValue))
                {
                    return i; // Insert before the first auto-generated profile
                }
            }

            return Profiles.Count;
        }

        private static bool IsAutoGeneratedProfileName(string name)
        {
            return System.Text.RegularExpressions.Regex.IsMatch(name, @"^Profile \d+$");
        }

        public bool TryAddProfileAtPosition(int position)
        {
            var profileName = GenerateProfileName();
            if (!profilesModel.TryAddNewDefault()) return false;

            // Move the newly added profile to the specified position
            var newProfile = profilesModel.Elements[^1];
            profilesModel.TryRemoveElement(newProfile);

            // Ensure position is within bounds
            int clampedPosition = Math.Max(1, Math.Min(position, profilesModel.Elements.Count));
            profilesModel.TryInsert(clampedPosition, newProfile);

            // Set the name
            newProfile.Name.TryUpdateModelDirectly(profileName);

            return true;
        }

        private bool TryAddProfileWithName(string profileName)
        {
            if (string.IsNullOrEmpty(profileName)) return false;

            if (!profilesModel.TryAddNewDefault()) return false;

            // Set the name of the newly added profile
            var newProfile = profilesModel.Elements[^1];
            return newProfile.Name.TryUpdateModelDirectly(profileName);
        }

        private string GenerateProfileName()
        {
            for (int i = 1; i <= MaxProfileAttempts; i++)
            {
                string name = $"Profile {i}";
                if (!profilesModel.TryGetElement(name, out _))
                {
                    return name;
                }
            }
            return string.Empty;
        }

        private async Task ProcessOperationQueue()
        {
            if (isProcessingQueue) return;

            isProcessingQueue = true;

            try
            {
                while (pendingOperations.TryDequeue(out var operation))
                {
                    await operationQueue.WaitAsync();
                    try
                    {
                        await operation();
                    }
                    finally
                    {
                        operationQueue.Release();
                    }
                }
            }
            finally
            {
                isProcessingQueue = false;
            }
        }

        private async Task WaitForAnimationsToComplete()
        {
            if (profileListView != null)
            {
                if (!profileListView.AreAnimationsActive)
                {
                    return;
                }

                var tcs = new TaskCompletionSource<bool>();

                void OnPropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
                {
                    if (e.PropertyName == nameof(profileListView.AreAnimationsActive) && !profileListView.AreAnimationsActive)
                    {
                        tcs.TrySetResult(true);
                    }
                }

                profileListView.PropertyChanged += OnPropertyChanged;

                try
                {
                    // Double-check in case animations completed between the initial check and event subscription
                    if (!profileListView.AreAnimationsActive)
                    {
                        return;
                    }

                    await tcs.Task;
                }
                finally
                {
                    profileListView.PropertyChanged -= OnPropertyChanged;
                }
            }
            else
            {
                await Task.Delay(400);
            }
        }


        public bool RemoveProfile(BE.IProfileModel profile) => profile != null && profilesModel.TryRemoveElement(profile);


        public void Dispose()
        {
            operationQueue?.Dispose();
        }
    }
}